// Builds supabase/migrations/0202_free_text_seed.sql from the CSVs in
// supabase/seed/free-text/ — the CSVs are what people review and edit.
// Run: node scripts/free-text/build-seed.mjs
// Seed rows only (source 'seed'); words admins add in review ('learned') are
// never touched, and re-running the migration leaves existing rows alone.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const dir = join(root, 'supabase', 'seed', 'free-text')

function csv(name) {
  const [head, ...lines] = readFileSync(join(dir, name), 'utf8').split(/\r?\n/).filter(l => l.trim())
  const cols = head.split(',')
  return lines.map(l => {
    const cells = l.split(',')
    if (cells.length !== cols.length) throw new Error(`${name}: expected ${cols.length} columns: ${l}`)
    return Object.fromEntries(cols.map((c, i) => [c, cells[i].trim()]))
  })
}
const q = v => v === '' || v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`
const n = v => v === '' || v == null ? 'null' : String(Number(v))
const b = v => v === 'true' ? 'true' : 'false'

const out = []
out.push(`-- 0202: starter vocabulary for 0201's matcher. GENERATED by
-- scripts/free-text/build-seed.mjs from supabase/seed/free-text/*.csv — edit
-- the CSVs (they are what gets reviewed), then re-run the script.
-- Duplicates after normalisation are skipped, so typos that normalise to the
-- same word are harmless.
`)
const block = (table, cols, rows, conflict) => {
  if (!rows.length) return
  out.push(`insert into ${table} (${cols.join(', ')}) values`)
  out.push(rows.map(r => `  (${r.join(', ')})`).join(',\n'))
  out.push(`on conflict ${conflict} do nothing;\n`)
}

block('intent_keywords', ['term', 'intent', 'speciality', 'lab_test_hint', 'weight', 'source'],
  csv('intent_keywords.csv').map(r => [q(r.term), q(r.intent), q(r.speciality), q(r.lab_test_hint), n(r.weight || 1), `'seed'`]),
  "(normalized_term, intent, coalesce(speciality, ''))")
block('emergency_keywords', ['term', 'severity', 'source'],
  csv('emergency_keywords.csv').map(r => [q(r.term), q(r.severity), `'seed'`]), '(normalized_term)')
block('negation_terms', ['term', 'negates'],
  csv('negation_terms.csv').map(r => [q(r.term), q(r.negates)]), '(normalized_term)')
block('time_expressions', ['term', 'day_offset', 'time_window', 'is_urgent'],
  csv('time_expressions.csv').map(r => [q(r.term), n(r.day_offset), q(r.time_window), b(r.is_urgent)]), '(normalized_term)')
block('location_aliases', ['alias', 'pin_code', 'location_name', 'location_name_hi', 'source'],
  csv('location_aliases.csv').map(r => [q(r.alias), q(r.pin_code), q(r.location_name), q(r.location_name_hi), `'seed'`]), '(normalized_alias)')

writeFileSync(join(root, 'supabase', 'migrations', '0202_free_text_seed.sql'), out.join('\n'))
console.log('wrote supabase/migrations/0202_free_text_seed.sql')
